defaultProject: powerbi-integration-306012
defaultLocation: eu-west3
defaultDataset: imdb
defaultAssertionDataset: imdb_assertions
dataformCoreVersion: 3.0.0
vars:
    LOAD_GCS_BUCKET: quickstart345-test/imdb
    RAW_DATA: imdb_staging
    TARGET_DATA: imdb