dataformCoreVersion: 3.0.0-beta.4
defaultProject: winter-dataform
defaultLocation: australia-southeast1
defaultDataset: imdb
defaultAssertionDataset: imdb_assertions
vars:
    LOAD_GCS_BUCKET: winter-data/imdb
    RAW_DATA: imdb_staging
    TARGET_DATA: imdb
